# nixpacks.toml
# Laravel 12 + Node + Railway
# Sin base de datos

[phases.setup]
nixPkgs = ["php84", "nodejs_20"]

[phases.install]
commands = [
  "export COMPOSER_ALLOW_SUPERUSER=1",
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm ci"
]

[phases.build]
commands = [
  "npm run build",
  "npm run build:ssr",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan optimize",
  "chmod -R 777 storage bootstrap/cache"
]

[phases.start]
[phases.start]
commands = [
  "php -S 0.0.0.0:$PORT -t public"
]